project:
  type: book

book:
  title: "Metody przetwarzania i analizy danych w R"
  author: "Łukasz Wawrowski"
  date: "02/24/2023"
  favicon: favicon.png
  chapters:
    - index.qmd
    - 01-eda.qmd
    - 02-testy.qmd
    - 03-klasyfikacja.qmd
    - 04-regresja.qmd
    - 05-grupowanie.qmd

format:
  html:
    theme: cosmo
    toc-title: "Spis treści"
