---
title: "Analiza struktury"
author: "Łukasz Wawrowski"
date: ""
output:
  xaringan::moon_reader:
    css: ["default.css", "default-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false


---

# Rozgrzewka

1. Utwórz nowy projekt w RStudio o nazwie zajęcia `adr20181117`.
2. Utwórz nowy skrypt R i wczytaj pakiety `tidyverse` i `readxl` - możliwe, że trzeba będzie je zainstalować.
3. Ze strony http://www.wawrowski.edu.pl/adr/ pobierz plik `Rossmann.xlsx` i z wykorzystaniem funkcji `read_xlsx()` przypisz ten zbiór do obiektu o nazwie `rossmann`.
4. Z wykorzystaniem funkcji `count()` sprawdź ile obserwacji znajdowało się w każdej grupie zdefiniowanej przez zmienną `sklep_asort`.

---

# Analiza struktury

**Kompleksowa analiza struktury** oznacza wyczerpujący opis cech zbiorowości statystycznej. Do charakterystyk najczęściej wykorzystywanych przy opisie struktury zbiorowości należą:

- miary przeciętne - służące do określania tej wartości zmiennej opisanej przez rozkład, wokół której skupiają się pozostałe wartości zmiennej,
- miary rozproszenia (dyspersji) - służące do badania stopnia zróżnicowania wartości zmiennej,
- miary asymetrii - służące do badania asymetrii rozkładu,
- miary koncentracji - służące do analizy stopnia skupienia poszczególnych jednostek wokół średniej.

---

# Przykład

Przeprowadź kompleksową analizę struktury dla sprzedaży w dwóch wybranych sklepach.

---

# Korelacje

Korelacja [łac.], mat. wzajemne powiązanie, współzależność zjawisk lub obiektów.

- korelacja cech jakościowych - statystyka $\chi^2$
- korelacja cech ciągłych - współczynnik korelacji liniowej Pearsona

---

# Przykład

Jak silna jest zależność pomiędzy przedziałami sprzedaży wyznaczonymi przez średnią a występowaniem promocji w sklepach?

Ile wynosi współczynnik korelacji liniowej Pearsona pomiędzy sprzedażą a liczbą klientów?

---

class: center, middle, inverse

# Pytania?