---
title: "Metody przetwarzania <br>i analizy danych"
subtitle: "Badania eksploracyjne"
author: "&copy; Łukasz Wawrowski"
date: ""
output:
  xaringan::moon_reader:
    css: ["default.css", "default-fonts.css"]
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r include=FALSE}
library(tidyverse)
library(countdown)
```

# Zbiór danych - [pracownicy](http://www.wawrowski.edu.pl/data/pracownicy.xlsx)

- id - kod pracownika
- plec - płeć pracownika (0 - mężczyzna, 1 - kobieta)
- data_urodz - data urodzenia
- edukacja - wykształcenie (w latach nauki)
- kat_pracownika - grupa pracownicza (1 - specjalista, 2 - menedżer, 3 - konsultant)
- bwynagrodzenie - bieżące wynagrodzenie
- pwynagrodzenie - początkowe wynagrodzenie
- staz - staż pracy (w miesiącach)
- doswiadczenie - poprzednie zatrudnienie (w miesiącach)
- zwiazki - przynależność do związków zawodowych (0 - nie, 1 - tak)
- wiek - wiek (w latach)

---

# Eksploracyjna analiza danych

Explanatory Data Analysis (EDA):

- opis

- wizualizacja

- badanie bez zakładania hipotez badawczych

---

# Pakiety

[The Landscape of R Packages for Automated Exploratory Data Analysis](https://journal.r-project.org/archive/2019/RJ-2019-033/index.html)

[summarytools](https://cran.r-project.org/web/packages/summarytools/vignettes/Introduction.html) - najczęściej pobierany pakiet 

- `view(dfSummary(zbior))` - wyświetla podsumowanie zawierające kilka statystyk opisowych, częstości, histogram i braki danych

- `freq(zbior$zmienna)` - wyświetla tabelę częstości

- `descr(zbior)` - wyświetla zestaw 15 statystyk opisowych

---

# Statystyki opisowe

- średnia (mean) - przeciętna wartość cechy
- odchylenie standardowe (std. dev) - o ile wartości cechy odchylają się średnio od średniej
- minimum (min) - minimalna wartość cechy
- kwartyl pierwszy (Q1) - 25% obserwacji ma wartości poniżej Q1, a 75% obserwacji powyżej
- mediana (median) - wartość środkowa, 50% obserwacji ma wartości poniżej Q1, a 50% obserwacji powyżej
- kwartyl trzeci (Q3) - 75% obserwacji ma wartości poniżej Q3, a 25% obserwacji powyżej
- maksimum (max) - maksymalna wartość cechy
- odchylenie medianowe (MAD) - mediana odchyleń od mediany
- rozstęp międzykwartylowy (IQR) - różnica pomiędzy trzecim i pierwszym kwartylem
- współczynnik zmienności (CV) - udział odchylenia standardowego w średniej wartości cechy (w %)
- skośność (skewness) - asymetria rozkładu cechy, $< 0$ - lewostronna, $> 0$ - prawostronna, $= 0$ - symetryczny
- błąd standardowy skośności (se.skewness)
- kurtoza (kurtosis) - skupienie wartości wokół średniej, $< 0$ - słabe, $> 0$ - silne, $= 0$ - normalne
- liczba obserwacji bez brakóW danych (N.Valid)
- odsetek obserwacji bez brakóW danych (Pct.Valid)

---

class: inverse, center, middle

# Pytania?